### ISSUE TITLE
Update to v1.20.4

### ISSUE THREAD

**Issue by thislooksfun** [Midnighttigger/MT-CT-D#2]
The pack on Modrinth says it supports v1.20.4, but when I try to add it the game says that it's incompatible ("made for an older version of Minecraft"). It would be really nice to have this pack working on the latest version.

**Comment by Midnighttigger** [comment]
You can ignore that, it should load perfectly on 1.20.4

**Comment by Midnighttigger** [comment]
its because I only specified 1 resource pack version instead of specifying multiple

**Comment by Midnighttigger** [comment]
https://modrinth.com/resourcepack/mt-ct-d/versions
did it ages ago but finally closing this issue
