### ISSUE TITLE
textures are broken

### ISSUE THREAD

**Issue by 69IDU420** [Midnighttigger/MT-CT-D#5]
![2024-09-01_22 33 19](https://github.com/user-attachments/assets/72c53b4b-a36e-40e6-bc2e-c887524bb799)
![2024-09-01_22 33 00](https://github.com/user-attachments/assets/2c113d8a-72f4-409f-b55a-a01cd21000ed)

**Comment by Midnighttigger** [comment]
Make sure to have Fusion Connected Textures mod
https://modrinth.com/mod/fusion-connected-textures
https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures

**Comment by 69IDU420** [comment]
Oh .. didn't realise that was needed. Thanks I will download that now
